### PR TITLE
add two files to shares js repo

### PR DESCRIPTION
**Pull request by samthomson**
one file for the popup menus, and one file for utility functions.

The utility functions are exported so as not to get marooned in/on a scope island once bundled with gulp.
Locally I have integrated this repo as a submodule to the status.im project, which works nicely enough.
If/when this PR is merged, I can then submit PRs on the three static sites making use of shared-js code.
I would then also propose I create an issue to further dissect the JS and break it up most elegantly, of which is beyond the remit of this task which focuses on the menu code.

### CODE REVIEW

**Comment by samthomson** [comment]
@andytudhope I guess I never tagged you for remove on this one. This is related to https://github.com/status-im/status.im/issues/168 where we looked to consolidate JS across static sites. What do you think? If it can be merged I can then submit relating PRs on the static sites themselves.

**Comment by samthomson** [comment]
review**

**Comment by andytudhope** [comment]
Hi @samthomson and happy new year ❤️ Apologies for the delay here - I was running Merry Merkle and then took some time off. I am happy with the approach here, so let's get those PRs submitted to the other repos when you can 👍

**Comment by samthomson** [comment]
Same to you, and no worries :upside_down_face:

**Pull request merged**
